version: '3.9'
services:
  app:
    build: .
    container_name: app
    image: app
    environment:
      TWITTER_ACCESS_KEY: '1234'
      TWITTER_SECRET_KEY: '4321'
    ports:
      - 8080:8080

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app
